Chore/JSSNMSHDD-2797 initialize
nmshd/cns-app-web pull request #1
Opened 2022-01-17 16:30 UTC by jkoenig134

2022-01-17 17:53 UTC, stnmtz requested changes

2022-01-17 17:53 UTC, stnmtz commented on package.json
> +    "version": "1.0.0",
Ich glaube wir sollten mit 2.0.0 anfangen, ansonsten haben wir ein Problem mit der App Version in den Stores

2022-01-17 17:53 UTC, stnmtz commented on ui5.yaml
> +  name: cns-app-blueprint
cns-app-web

2022-01-17 17:53 UTC, stnmtz commented on webapp/flows/account/relationship/AttributesSent.controller.js
> +        return RelationshipController.extend("nmshd.app.flows.account.relationship.Attributes", {
RelationshipController.extend("nmshd.app.flows.account.relationship.AttributesSent", {

2022-01-17 17:53 UTC, stnmtz commented on webapp/flows/account/relationship/AttributesReceived.controller.js
> +        return RelationshipController.extend("nmshd.app.flows.account.relationship.Attributes", {
return RelationshipController.extend("nmshd.app.flows.account.relationship.AttributesReceived", {

2022-01-18 07:35 UTC, jkoenig134 commented on package.json
> +    "version": "1.0.0",
Hab ich extra nicht gemacht, dann wird es einfacher zur neuen Build-Pipeline zu migrieren

2022-01-18 07:50 UTC, stnmtz submitted a review, later dismissed

2022-01-18 08:29 UTC, stnmtz approved these changes

2022-01-18 08:30 UTC, merged