Feature/jssnmshdd 3065 enable response to requests
nmshd/cns-app-web pull request #24
Opened 2022-07-22 20:55 UTC by stnmtz

2022-07-25 08:24 UTC, jkoenig134 requested changes

2022-07-25 08:24 UTC, jkoenig134 commented on webapp/flows/account/relationships/Template.controller.js
> +                            if (template.content && template.content.ifRelationshipExists) {
wieso kommt das den jetzt neu rein?

2022-07-25 08:25 UTC, stnmtz commented on webapp/flows/account/relationships/Template.controller.js
> +                            if (template.content && template.content.ifRelationshipExists) {
Weil ich zu rigoros gelöscht hatte :D

2022-07-25 09:00 UTC, stnmtz commented on webapp/flows/account/relationships/Template.controller.js
> +                            if (template.content && template.content.ifRelationshipExists) {
nvm, mein Fehler

2022-07-25 09:22 UTC, jkoenig134 approved these changes

2022-07-25 10:26 UTC, tnotheis requested changes
@stnmtz Du weißt, dass die Runtime noch keinen Rejectvon Requests aus Relationship Templates unterstützt?

2022-07-25 10:26 UTC, tnotheis commented on webapp/i18n/i18n.properties
> +dvo.attribute.name.BirthYear=Year of Bith
Typo (Birth)

2022-07-25 10:26 UTC, tnotheis commented on webapp/i18n/i18n.properties
> +dvo.attribute.name.HouseNumber=HouseNumber
Fehlendes Leerzeichen? Oder ist das Absicht?

2022-07-25 10:26 UTC, tnotheis commented on webapp/i18n/i18n.properties
> +dvo.attribute.name.ZipCode=ZipCode
Fehlendes Leerzeichen? Oder ist das Absicht?

2022-07-25 12:24 UTC, tnotheis commented on webapp/core/App.js
> +                if (prefix === "nmshd://qr#" || prefix === "nmshd://tr#") {
Wieso hast du beim Entwickeln keine Prefixes?

2022-07-26 06:53 UTC, tnotheis approved these changes

2022-07-26 06:54 UTC, jkoenig134 approved these changes

2022-07-26 07:33 UTC, merged