Feature/jssnmshdd 3099 show responses of requests
nmshd/cns-app-web pull request #34
Opened 2022-08-26 08:14 UTC by stnmtz

2022-08-26 08:34 UTC, jkoenig134 submitted a review, later dismissed

2022-08-26 08:34 UTC, jkoenig134 commented on webapp/flows/account/relationship/Request.controller.js
> +                console.log(this.request)
Logs vielleicht wieder weg

2022-08-30 06:51 UTC, jkoenig134 requested changes

2022-08-30 06:51 UTC, jkoenig134 commented on webapp/core/controls/requests/RequestItemRenderer.js
> +                            if (item.type) {
item.type ist doch nicht optional, oder? Selbst wenn es optional ist ist das if unnötig, ich würde auch gerne wissen wenn undefined oder null als type bearbeitet werden. 

Unten das selbe.

2022-08-30 06:52 UTC, stnmtz commented on webapp/core/controls/requests/RequestItemRenderer.js
> +                            if (item.type) {
Es kamen tatsächlich ein paar log statements mit undefined raus, deswegen die if Abfrage. Ist auf meinen Zettel das anzuschauen

2022-08-30 07:31 UTC, jkoenig134 approved these changes

2022-08-30 07:59 UTC, merged